### ISSUE TITLE
extendability

### ISSUE THREAD

**Issue by infario** [archinmodi/Jquery-Theme-Switcher#1]
Nice work!. The switcher applied for a single element, can we make it apply for whole page. Is there any option to load external css files based on color skins like this
{layout:{'boxed':css-boxed.css,'wide': 'css-wide.css'},
colors:{colorcode1:cssfile1.css,colorcode2:cssfile2.css}
}

something with above settings it can be extended to any level.

**Comment by archinmodi** [comment]
a user needs to do more coding for the CSS file but my prepose is user can less coding for css file.users will be more coding in plugin have no meaning.

**Comment by infario** [comment]
ok.. maybe i am wrong, Do you have implemented this in any site/app ? so a practical view can be helpful

**Comment by archinmodi** [comment]
http://archin-modi.github.io/Jquery-Theme-Switcher/

**Comment by infario** [comment]
ok.. I have created my own version which template designers to add color schemes and use the plugin to change it:

https://infario.github.io/colorpanel/

**Comment by archinmodi** [comment]
i think your plugin add in https://themeforest.net

**Comment by infario** [comment]
As for now i dont have any plan to sell the plugin. Just want it to be open source

**Comment by archinmodi** [comment]
can you suggest me ,how to improve my plugin design?

**Comment by archinmodi** [comment]
**colorpanel** design is awesome...

**Comment by infario** [comment]
Thanks!.. Your plugin designed for inline editing right. It can be improved just like wordpress customizer for static pages

**Comment by archinmodi** [comment]
my plugin css file and templet css files are override. so, what can i do

**Comment by infario** [comment]
May be the customization can be stored in json file and update the dom on load. I will do some research and let you know
